### ISSUE TITLE
eos balance 会溢出

### ISSUE THREAD

**Issue by ethgamble** [dabdevelop/playerone#1]
### 问题描述：
eosio_assert(real_eos_balance == game_itr->reserve + game_itr->insure, "eos balance leaks");
### 问题区域：
buy，sell，burn

**Comment by dabdevelop** [comment]
This bug is fixed at commit [f0e7293](https://github.com/dabdevelop/playerone/commit/f0e7293b7b878f475012eb4c3c9458e4c986565e)
