### ISSUE TITLE
在transfer函数中没有判断代币合约地址

### ISSUE THREAD

**Issue by ethgamble** [dabdevelop/playerone#3]
### 问题描述

1. apply函数允许两个代币合约地址转来的代币进行同步；
2. transfer函数只判断了代币的符号，但是没有判断具体是哪个代币合约同步的消息；
3. 可能出现攻击行为，从eosio.token转来游戏代币，或者从游戏代币合约转入符号也为EOS的代币。

### 问题区域
apply，transfer

**Comment by dabdevelop** [comment]
commit [ce3c2c3](https://github.com/dabdevelop/playerone/commit/ce3c2c36b4758ff4d6b10bd1d9c5a1fe8e90f539)  fixed this bug.
